language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t claragaillard59/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true claragaillard59/docker-react npm run test